name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: 
      ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
       submodules: recursive
    - name: Build debug
      run: cargo build --verbose
    - name: Build release
      run: cargo build --release
